routes/web.php
<?php

Auth::routes(['verify' => true]);
Route::mailgunWebhooks('webhooks/mailgun');

Route::get('/', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth', 'verified']], function () {
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

    Route::get('/customersign/{token}', 'EstimateController@customersign')->name('customersign');
    Route::post('/customersign', 'EstimateController@customerDosign');
    Route::post('/customersign/verify', 'EstimateController@customerVerify');

    /*Project Routes*/
    //Route::resource('projects', 'ProjectController')->except(['destroy']);
    Route::get('/projects', 'ProjectController@index')->name('projects.index');
    Route::get('projects/create', 'ProjectController@create')->name('projects.create');
    Route::post('projects/{step}', 'ProjectController@store')->name('projects.steps.store');
    //Route::get("/testemail",'ProjectController@basic_email');

    Route::group(['prefix' => 'estimator'], function () {
        Route::get('/buildlists', 'BuildListController@index')->name('estimator.buildlists');
        Route::get('/buildlists/build', 'BuildListController@create')->name('estimator.buildlists.build');
        Route::get('/{step?}', 'EstimatorController@index')->name('estimator.index');

        Route::get('/{project}/structure-details', 'EstimatorController@getStructureDetails')->name('estimator.structure_details');
        Route::post('/{project}/structure', 'EstimatorController@storeStructure')->name('estimator.structure.store');

        Route::get('/{project}/roof-selector', 'EstimatorController@roofSelector')->name('estimator.roof_selector');
        Route::post('/{project}/roof-selector', 'StructureController@storeRoofType')->name('estimator.roof_selector');

        Route::post('/{project}/estimate', 'EstimatorController@estimate')->name('estimator.estimate');
    });

    Route::get('/estimator/numbers', 'EstimateController@numbers')->name('numbers');

    Route::post('/estimator/calculate', 'EstimateController@store');
    Route::post('/estimator/store', 'PropertyController@store')->name('properties.store');
    Route::get('/estimator/create-estimate', 'EstimateController@create')->name('myestimates');
    Route::get('/estimator/estimate-figures', 'EstimateController@showCalculationResult')->name('estimate-figures');
    Route::get('/estimator/generateProposal', 'EstimateController@generateProposal')->name('generateProposal');
    /*proposal send*/
    Route::post('/estimator/generateProposal/{id}/send', 'EstimateController@generateProposalSend')->name('generateProposalSend');

    /*Harvester Views*/
    Route::get('/harvester/market', 'HarvesterController@market')->name('market');                      // Gabe working on this interface
    Route::get('/harvester/candidates', 'HarvesterController@candidates')->name('candidates');          // Gabe working on this interface

    Route::get('/estimator/generatePDF', 'EstimateController@generatePDF')->name('generatePDF');


    Route::get('/signer/docs', 'DocumentsController@index')->name('docs');

    Route::post('appointments/{appointment}/update-time', 'AppointmentController@updateTime');
    Route::resource('appointments', 'AppointmentController');

    Route::resource('users', 'UserController');
    Route::resource('materials', 'MaterialController');

    Route::get('tasks/{task}/complete', 'TaskController@complete')->name('tasks.complete');
    Route::resource('tasks', 'TaskController')->only(['index', 'create', 'store']);

    ## Gabe Playground
    Route::get('/email', 'HomeController@email')->name('email');        // Gabe messing around with Sendgrid

    /*Project Routes*/
    Route::resource('customers', 'CustomerController')->except(['destroy']);

    /* Maximus routes */
    Route::group(['prefix' => 'maximus/claims'], function () {
        Route::get('/', 'MaximusController@index')->name('maximus.claims.index');
        Route::get('new', 'MaximusController@create')->name('maximus.claims.create');
        Route::post('/{step}', 'MaximusController@store')->name('maximus.claims.step.store');
//        Route::post('new', 'MaximusController@store')->name('maximus.claims.store');
        Route::get('{claim}/show', 'MaximusController@show')->name('maximus.claims.show');
        Route::post('{claim}/update', 'MaximusController@update')->name('maximus.claims.update');
        Route::post('{claim}/temp-repair', 'MaximusController@tempRepairStore')->name('maximus.temp_repair.store');
        Route::post('{claim}/supplement', 'MaximusController@supplement')->name('maximus.supplement.store');
        Route::post('{claim}/record-correspondence', 'MaximusController@recordCorrespondence')->name('maximus.record_correspondence.store');
        Route::post('{claim}/escalate', 'MaximusController@escalate')->name('maximus.escalate');
        Route::get('{claim}/test', 'MaximusController@test');
    });

    Route::resource('insurance-carriers', 'InsuranceCarrierController')->names([
        'create' => 'insurance_carriers.create',
        'store' => 'insurance_carriers.store',
        'index' => 'insurance_carriers.index',
        'destroy' => 'insurance_carriers.destroy',
        'update' => 'insurance_carriers.update',
        'show' => 'insurance_carriers.show',
        'edit' => 'insurance_carriers.edit',
    ]);

    ## Khawar working area
    Route::group(['prefix' => 'settings'], function () {
        Route::view('/company', 'settings/company/show')->name('settings.company.show');
        Route::view('/company/edit', 'settings/company/edit')->name('settings.company.edit');
    });

    Route::name('templates.')->prefix('templates')->group(function () {
        Route::get('emails/{template}/changeStatus', 'EmailTemplateController@changeStatus')->name('emails.change_status');

        Route::resource('emails', 'EmailTemplateController')->parameters(['emails' => 'template']);
    });


    Route::get('constants', 'GroupConstantController')->name('constants.index');
    Route::resource('placeholders', 'PlaceholderController');

    Route::get('emails/odmails', 'OdMailController@index')->name('emails.odmails');
    Route::get('emails/odmail/{odmail}', 'OdMailController@show')->name('emails.odmails.show');
    Route::get('emails/odmail/{odmail}/resend', 'OdMailController@resend')->name('emails.odmails.resend');
    Route::post('emails/odmail/{odmail}/forward', 'OdMailController@forward')->name('emails.odmails.forward');

    Route::resource('campaigns', 'CampaignController');
    Route::get('campaigns/{campaign}/recipients', 'CampaignController@recipients')->name('campaigns.recipients');

    Route::get('developer-tools/logs', 'DeveloperTools\LogsController@index')->name('developer_tools.logs');
    Route::get('developer-tools/logs/{file}', 'DeveloperTools\LogsController@show')->name('developer_tools.logs.show');
    Route::delete('developer-tools/logs/{file}', 'DeveloperTools\LogsController@truncate')->name('developer_tools.logs.truncate');

});
Route::view('/frontend', 'frontend/frontend')->name('frontend');

app/Campaign.php
<?php

namespace App;

use App\MediaLibrary\InteractsWithMedia;
use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia;

class Campaign extends Model implements HasMedia
{
    use InteractsWithMedia;

    protected $fillable = ['template_id', 'name', 'description', 'columns', 'status',];

    protected $casts = [
        'columns' => 'array'
    ];

    public function registerMediaCollections(): void
    {
        $this->addMediaCollection('damage-photos');
        $this->addMediaCollection('documents');
    }

    public function recipients()
    {
        return $this->hasMany(CampaignRecipient::class);
    }

    public function template()
    {
        return $this->belongsTo(Template::class);
    }

    public function getStats($status = null, $get_percentage = false)
    {
        $column = "{$status}_at";

        $total_recipients = $this->recipients->count();

        if (!$status) {
            $count = $this->sent_emails;
        } else {
            $count = $this->recipients->whereNotNull($column)->count();
        }

        $percentage = $total_recipients ? round($count / $total_recipients * 100) . '%' : '0%';

        return $get_percentage ? $percentage : $count;
    }
}

app/Http/Controllers/CampaignController.php
<?php

namespace App\Http\Controllers;

use App\Campaign;
use App\Jobs\RunCampaign;
use App\Mail\CampaignMail;
use App\Template;
use Illuminate\Http\Request;
use Illuminate\Support\Arr;
use Illuminate\Support\Str;

class CampaignController extends Controller
{
    public function index()
    {
        $campaigns = Campaign::with('recipients')->withCount('recipients')->get();
        return view('campaign.index', compact('campaigns'));
    }

    public function create()
    {
        $templates = Template::type('campaign')->get();
        return view('campaign.create', compact('templates'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'template_id' => 'required',
            'recipients' => [
                'required',
                function ($attribute, $value, $fail) {
                    $this->validateCsv($attribute, $value, $fail);
                },
            ]
        ]);

        $campaign = Campaign::create($request->except('recipients'));

        $campaign->addMediaFromRequest('recipients')->toMediaCollection();

        RunCampaign::dispatch($campaign);
        return redirect()->route('campaigns.index')->with('Campaign Created Successfully');
    }

    public function show(Campaign $campaign)
    {
        return view('campaign.show', compact('campaign'));
    }

    public function recipients(Campaign $campaign)
    {
        $recipients = $campaign->recipients()->paginate(30);
        return view('campaign.recipients', compact('recipients', 'campaign'));
    }


    private function validateCsv($attribute, $value, $fail)
    {
        $filename = $value->getPathName();
        $delimiter = ',';

        $header = null;
        if (($handle = fopen($filename, 'r')) !== false) {
            while (($row = fgetcsv($handle, 1000, $delimiter)) !== false) {
                if (!$header){
                    $header = $row;
                    break;
                }
            }
            fclose($handle);
        }

        if (! in_array('email', $header)) {
            $fail($attribute . ' file must contains a column named email.');
        }
    }

    private function csvToArray($filename = '', $columns = array(), $delimiter = ',')
    {
        if (!file_exists($filename) || !is_readable($filename))
            return false;

        $header = null;

        $data = array();
        if (($handle = fopen($filename, 'r')) !== false) {
            while (($row = fgetcsv($handle, 1000, $delimiter)) !== false) {
                if (!$header)
                    $header = $row;
                else
                    $data[] = array_combine($header, $row);
            }
            fclose($handle);
        }

        $columns = $columns ? array_map(function ($value){
            return strtolower($value);
        }, $columns) : $columns;

        return collect($data)
            ->filter(function ($data) {
                return array_sum($data) && $data['email'];
            })
            ->map(function ($data) {
                return array_change_key_case($data, CASE_LOWER);
            })
            ->map(function ($data) use ($columns) {
                return $columns ? Arr::only($data, $columns) : $data;
            })
            ->filter(function ($data) {
                $job_type = $data['job type'];
                return
                    $job_type
                    &&  ! Str::contains($job_type, ['Shingle', 'Metal', 'Flat', 'TPO', 'Maintenance', 'Service', 'Warranty', 'Low Slope', 'Replacement'])
                    && ! Str::contains($data['created by'], 'Pedro');
            });
    }
}

resources/views/campaign/create.blade.php
@extends('layouts.backend')

@section('styles')
    <link href="{{ asset('js/plugins/bootstrap-fileinput/css/fileinput.css') }}" media="all" rel="stylesheet" type="text/css"/>
    <link href="{{ asset('js/plugins/bootstrap-fileinput//themes/explorer-fas/theme.css') }}" media="all" rel="stylesheet" type="text/css"/>
    <link rel="stylesheet" type="text/css" href="{{asset('js/plugins/bs-tagsinput/tagsinput.css')}}">
@endsection

@section('breadcrumbs')
    <a class="breadcrumb-item" href="javascript:void(0)">Campaigns Manager</a>
@endsection

@section('breadcrumb-active', 'New Campaign')

@section('content')
    <div class="block">
        <div class="block-header block-header-default">New Campaign</div>
        <div class="block-content">
            @include('includes.partials.errors')
            <form action="{{ route('campaigns.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="form-row">
                    <div class="form-group col-6">
                        <label for="name">Name</label>
                        <input type="text" id="name" name="name"
                               class="form-control @error('template_id') is-invalid @enderror"
                               value="{{ old('name') }}">
                        @include('includes.partials.error', ['field' => 'name'])
                    </div>
                    <div class="form-group col-6">
                        <label for="template_id">Campaign Template: </label>
                        <select class="form-control @error('template_id') is-invalid @enderror"
                                id="template_id" name="template_id">
                            <option value="">Select</option>
                            @foreach($templates as $template)
                                <option value="{{ $template->id }}"
                                    {{ old('template_id') == $template->id ? 'selected':'' }}>
                                    {{ $template->name }}
                                </option>
                            @endforeach
                        </select>
                        @include('includes.partials.error', ['field' => 'template_id'])
                    </div>
                    <div class="form-group col-12">
                        <label for="columns">Columns:</label>
                        <select id="columns"  name="columns[]" data-role="tagsinput" multiple
                               class="form-control @error('columns') is-invalid @enderror">
                            @if(old('columns'))
                                @foreach(old('columns') as $column)
                                    <option value="{{ $column }}">{{ $column }}</option>
                                @endforeach
                            @endif
                        </select>
                        @include('includes.partials.error', ['field' => 'columns'])
                    </div>
                    <div class="form-group col-12">
                        <label class="font-italic font-size-xs text-muted">Upload Excel File</label>
                        <input type="file" id="recipients" class="file-input form-control @error('aob') is-invalid @enderror"
                               name="recipients"  data-allowed-file-extensions='["csv", "pdf"]'>
                        @include('includes.partials.error', ['field' => 'recipients', 'class' => 'd-block'])
                    </div>
                </div>
                <div class="form-group col-12 text-right px-0">
                    <button type="submit" class="btn btn-success btn-sm">Create</button>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="{{ asset('js/plugins/bs-tagsinput/tagsinput.js') }}"></script>

    <script>
        jQuery(function () {
            Codebase.helper(['summernote', 'flatpickr', 'select2', 'tags-inputs']);
        });
    </script>

    @include('includes.common.bootstrap-fileinput')

@endsection

resources/views/campaign/index.blade.php
@extends('layouts.backend')

@section('breadcrumbs')
    <a class="breadcrumb-item" href="javascript:void(0)">Campaigns Manager</a>
@endsection
@section('breadcrumb-active', 'Index')

@section('styles')
@endsection

@section('content')
    <div class="block">
        <div class="block-header block-header-default">
            <h3 class="block-title">Campaigns List</h3>
        </div>
        <div class="block-content">
            <div class="table-responsive">
                <table class="table table-striped table-vcenter">
                    <thead>
                    <tr>
                        <th style="width: 10px">#</th>
                        <th>Name</th>
                        <th>Total Recipients</th>
                        <th>Emails Sent</th>
                        <th>Emails Delivered</th>
                        <th>Emails Opened</th>
                        <th>Emails Failed</th>
                        <th>Status</th>
                        <th style="width: 50px">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @forelse($campaigns as $campaign)
                        <tr>
                            <td>{{ $campaign->id }}</td>
                            <td>{{ $campaign->name }}</td>
                            <td>{{ $campaign->recipients_count }}</td>
                            <td>{{ $campaign->getStats('sent') }}</td>
                            <td>{{ $campaign->getStats('delivered') }}</td>
                            <td>{{ $campaign->getStats('opened') }}</td>
                            <td>{{ $campaign->getStats('failed') }}</td>
                            <td>
                                @if($campaign->status == 1)
                                    <span class="text-success">Finished</span>
                                @else
                                    <span class="text-info">Running</span>
                                @endif
                            </td>
                            <td class="text-center">
                                <div class="btn-group">
                                    <a href="{{ route('campaigns.show', $campaign ) }}"
                                       class="btn btn-sm btn-secondary"
                                       data-toggle="tooltip" title="Show">
                                        <i class="fad fa-eye"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="999" class="text-center">{{ app('constants')->constant('no_record') }}</td>
                        </tr>
                    @endforelse
                    </tbody>
                </table>

                {{--<div class="pagination justify-content-center">
                    {{ $claims->links() }}
                </div>--}}
            </div>
        </div>
    </div>
@endsection

@section('scripts')
@endsection

resources/views/campaign/recipients.blade.php
@extends('layouts.backend')

@section('content')
    <div class="block">
        <div class="block-header block-header-default">
            <h3 class="block-title">Campaign Recipients</h3>
        </div>
        <div class="block-content">
            <div class="table-responsive">
                <table class="table table-striped table-vcenter">
                    <thead>
                    <tr class="text-uppercase">
                        <th style="width: 10px">#</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Status</th>
                    </tr>
                    </thead>
                    <tbody>
                    @forelse($recipients as $recipient)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $recipient->name }}</td>
                            <td>{{ $recipient->email }}</td>
                            <td>{{ $recipient->status_text }}</td>
                        </tr>
                    @empty
                    @endforelse
                    </tbody>
                </table>

                <div class="pagination justify-content-center">
                    {{ $recipients->links() }}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/campaign/show.blade.php
@extends('layouts.backend')

@section('styles')
@endsection

@section('breadcrumbs')
    <a class="breadcrumb-item" href="javascript:void(0)">Campaigns Manager</a>
@endsection

@section('breadcrumb-active', 'Details')

@section('content')
    <div class="block">
        <div class="block-header block-header-default">
            <h3 class="block-title">{{ $campaign->name }}</h3>
            <div class="block-options">
                <a href="{{ route('campaigns.recipients', $campaign ) }}"
                   class="btn-block-option"
                   data-toggle="tooltip" title="See Recipients">
                    <i class="fal fa-list"></i>
                </a>
            </div>
        </div>
        <div class="block-content">
            <x-utils.progressbar :percentage="$campaign->getStats('sent', true)"/>
            <br>
            <div class="row items-push-2x text-center invisible" data-toggle="appear">
                <div class="col-6 col-md-3">
                    <x-utils.pie-chart
                        title="Emails Sent" :percentage="$campaign->getStats('sent', true)"
                        :count="$campaign->getStats('sent')" color="#ffca28">
                    </x-utils.pie-chart>
                </div>
                <div class="col-6 col-md-3">
                    <x-utils.pie-chart
                        title="Emails Delivered" :percentage="$campaign->getStats('delivered', true)"
                        :count="$campaign->getStats('delivered')" color="#3f9ce8">
                    </x-utils.pie-chart>
                </div>
                <div class="col-6 col-md-3">
                    <x-utils.pie-chart
                        title="Emails Opened" :percentage="$campaign->getStats('opened', true)"
                        :count="$campaign->getStats('opened')" color="#9ccc65">
                    </x-utils.pie-chart>
                </div>
                <div class="col-6 col-md-3">
                    <x-utils.pie-chart
                        title="Emails Failed" :percentage="$campaign->getStats('failed', true)"
                        :count="$campaign->getStats('failed')" color="#ef5350">
                    </x-utils.pie-chart>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="{{ asset('js/plugins/easy-pie-chart/jquery.easypiechart.min.js') }}"></script>
    {{--<script src="{{ asset('js/plugins/parkline/jquery.sparkline.min.js') }}"></script>
    <script src="{{ asset('js/plugins/chartjs/Chart.bundle.min.js') }}"></script>
    <script src="{{ asset('js/plugins/flot/jquery.flot.min.js') }}"></script>
    <script src="{{ asset('js/plugins/flot/jquery.flot.pie.min.js') }}"></script>
    <script src="{{ asset('js/plugins/flot/jquery.flot.stack.min.js') }}"></script>
    <script src="{{ asset('js/plugins/flot/jquery.flot.resize.min.js') }}"></script>--}}
    <script>
        jQuery(function () {
            Codebase.helpers(['easy-pie-chart']);
        });
    </script>
@endsection