routes/web.php
<?php

Auth::routes(['verify' => true]);
Route::mailgunWebhooks('webhooks/mailgun');

Route::get('/', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth', 'verified']], function () {
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

    Route::get('/customersign/{token}', 'EstimateController@customersign')->name('customersign');
    Route::post('/customersign', 'EstimateController@customerDosign');
    Route::post('/customersign/verify', 'EstimateController@customerVerify');

    /*Project Routes*/
    //Route::resource('projects', 'ProjectController')->except(['destroy']);
    Route::get('/projects', 'ProjectController@index')->name('projects.index');
    Route::get('projects/create', 'ProjectController@create')->name('projects.create');
    Route::post('projects/{step}', 'ProjectController@store')->name('projects.steps.store');
    //Route::get("/testemail",'ProjectController@basic_email');

    Route::group(['prefix' => 'estimator'], function () {
        Route::get('/buildlists', 'BuildListController@index')->name('estimator.buildlists');
        Route::get('/buildlists/build', 'BuildListController@create')->name('estimator.buildlists.build');
        Route::get('/{step?}', 'EstimatorController@index')->name('estimator.index');

        Route::get('/{project}/structure-details', 'EstimatorController@getStructureDetails')->name('estimator.structure_details');
        Route::post('/{project}/structure', 'EstimatorController@storeStructure')->name('estimator.structure.store');

        Route::get('/{project}/roof-selector', 'EstimatorController@roofSelector')->name('estimator.roof_selector');
        Route::post('/{project}/roof-selector', 'StructureController@storeRoofType')->name('estimator.roof_selector');

        Route::post('/{project}/estimate', 'EstimatorController@estimate')->name('estimator.estimate');
    });

    Route::get('/estimator/numbers', 'EstimateController@numbers')->name('numbers');

    Route::post('/estimator/calculate', 'EstimateController@store');
    Route::post('/estimator/store', 'PropertyController@store')->name('properties.store');
    Route::get('/estimator/create-estimate', 'EstimateController@create')->name('myestimates');
    Route::get('/estimator/estimate-figures', 'EstimateController@showCalculationResult')->name('estimate-figures');
    Route::get('/estimator/generateProposal', 'EstimateController@generateProposal')->name('generateProposal');
    /*proposal send*/
    Route::post('/estimator/generateProposal/{id}/send', 'EstimateController@generateProposalSend')->name('generateProposalSend');

    /*Harvester Views*/
    Route::get('/harvester/market', 'HarvesterController@market')->name('market');                      // Gabe working on this interface
    Route::get('/harvester/candidates', 'HarvesterController@candidates')->name('candidates');          // Gabe working on this interface

    Route::get('/estimator/generatePDF', 'EstimateController@generatePDF')->name('generatePDF');


    Route::get('/signer/docs', 'DocumentsController@index')->name('docs');

    Route::post('appointments/{appointment}/update-time', 'AppointmentController@updateTime');
    Route::resource('appointments', 'AppointmentController');

    Route::resource('users', 'UserController');
    Route::resource('materials', 'MaterialController');

    Route::get('tasks/{task}/complete', 'TaskController@complete')->name('tasks.complete');
    Route::resource('tasks', 'TaskController')->only(['index', 'create', 'store']);

    ## Gabe Playground
    Route::get('/email', 'HomeController@email')->name('email');        // Gabe messing around with Sendgrid

    /*Project Routes*/
    Route::resource('customers', 'CustomerController')->except(['destroy']);

    /* Maximus routes */
    Route::group(['prefix' => 'maximus/claims'], function () {
        Route::get('/', 'MaximusController@index')->name('maximus.claims.index');
        Route::get('new', 'MaximusController@create')->name('maximus.claims.create');
        Route::post('/{step}', 'MaximusController@store')->name('maximus.claims.step.store');
//        Route::post('new', 'MaximusController@store')->name('maximus.claims.store');
        Route::get('{claim}/show', 'MaximusController@show')->name('maximus.claims.show');
        Route::post('{claim}/update', 'MaximusController@update')->name('maximus.claims.update');
        Route::post('{claim}/temp-repair', 'MaximusController@tempRepairStore')->name('maximus.temp_repair.store');
        Route::post('{claim}/supplement', 'MaximusController@supplement')->name('maximus.supplement.store');
        Route::post('{claim}/record-correspondence', 'MaximusController@recordCorrespondence')->name('maximus.record_correspondence.store');
        Route::post('{claim}/escalate', 'MaximusController@escalate')->name('maximus.escalate');
        Route::get('{claim}/test', 'MaximusController@test');
    });

    Route::resource('insurance-carriers', 'InsuranceCarrierController')->names([
        'create' => 'insurance_carriers.create',
        'store' => 'insurance_carriers.store',
        'index' => 'insurance_carriers.index',
        'destroy' => 'insurance_carriers.destroy',
        'update' => 'insurance_carriers.update',
        'show' => 'insurance_carriers.show',
        'edit' => 'insurance_carriers.edit',
    ]);

    ## Khawar working area
    Route::group(['prefix' => 'settings'], function () {
        Route::view('/company', 'settings/company/show')->name('settings.company.show');
        Route::view('/company/edit', 'settings/company/edit')->name('settings.company.edit');
    });

    Route::name('templates.')->prefix('templates')->group(function () {
        Route::get('emails/{template}/changeStatus', 'EmailTemplateController@changeStatus')->name('emails.change_status');

        Route::resource('emails', 'EmailTemplateController')->parameters(['emails' => 'template']);
    });


    Route::get('constants', 'GroupConstantController')->name('constants.index');
    Route::resource('placeholders', 'PlaceholderController');

    Route::get('emails/odmails', 'OdMailController@index')->name('emails.odmails');
    Route::get('emails/odmail/{odmail}', 'OdMailController@show')->name('emails.odmails.show');
    Route::get('emails/odmail/{odmail}/resend', 'OdMailController@resend')->name('emails.odmails.resend');
    Route::post('emails/odmail/{odmail}/forward', 'OdMailController@forward')->name('emails.odmails.forward');

    Route::resource('campaigns', 'CampaignController');
    Route::get('campaigns/{campaign}/recipients', 'CampaignController@recipients')->name('campaigns.recipients');

    Route::get('developer-tools/logs', 'DeveloperTools\LogsController@index')->name('developer_tools.logs');
    Route::get('developer-tools/logs/{file}', 'DeveloperTools\LogsController@show')->name('developer_tools.logs.show');
    Route::delete('developer-tools/logs/{file}', 'DeveloperTools\LogsController@truncate')->name('developer_tools.logs.truncate');

});
Route::view('/frontend', 'frontend/frontend')->name('frontend');

app/Address.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Eloquent\SoftDeletes;

class Address extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'client_id', 'street', 'city', 'county', 'state', 'zip_code', 'country', 'addressable_type',
        'latitude', 'longitude', 'addressable_id', 'latitude', 'longitude','enhanced_data'
    ];

    protected $casts = [
        'enhanced_data' => 'array',
    ];

    public function addressable()
    {
        return $this->morphTo();
    }

    public function getFullAddressAttribute()
    {
        return implode(', ', $this->only(['street', 'city', 'state', 'zip_code']));
    }

}

app/Http/Controllers/MaximusController.php
<?php

namespace App\Http\Controllers;

use App\Client;
use App\Customer;
use App\Http\Requests\MaximusRequest;
use App\Jobs\ProcessMaximusClaimUploads;
use App\Mail\ForwardOdmail;
use App\Mail\Maximus\ClaimEscalated;
use App\Mail\Maximus\InfoSubmitted;
use App\Mail\Maximus\AobSubmitted;
use App\Mail\Maximus\TempRepairSubmitted;
use App\MaximusClaim;
use App\Media;
use App\Odmail;
use App\Placeholder;
use App\Property;
use App\Template;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;
use Mail;
use PDF;

class MaximusController extends Controller
{
    public function index()
    {
        $claims = MaximusClaim::with(['customer', 'property.address', 'status', 'estimator', 'mails'])->latest('id')->get();
        return view('maximus.index', compact('claims'));
    }

    public function create()
    {
        $data['uuid'] = \Str::orderedUuid()->toString();
        $data['adminDefinePlaceholders'] = Placeholder::all();
        $data['template'] = Template::type('email')->key('new_aob_submitted')->first();

        return view('maximus.create', $data);
    }

    public function store(Request $request, $step)
    {
        /*$claim = MaximusClaim::create([
              'user_id' => auth()->id(),
              'estimator_id' => $request->estimator_id ?? auth()->id(),
              'customer_id' => $customer->id,
              'insurance_carrier_id' => $request->insurance_carrier_id,
              'claim_number' => $request->claim_number,
              'policy_number' => $request->policy_number,
              'date_of_loss' => $request->date_of_loss,
              'aob_signed_on' => $request->aob_signed_on,
              'claim_type_id' => $request->claim_type_id,
              'minimum_damaged_units' => $request->minimum_damaged_units,
          ]);*/
        $request->merge([
            'user_id' => auth()->id(),
            'estimator_id' => $request->estimator_id ?? auth()->id(),
        ]);

        $claim = $request->claim_id ? MaximusClaim::find($request->claim_id) : null;
        $customer = is_object($claim) ? $claim->customer : null;
        $property = is_object($claim) && isset($claim->property) ? $claim->property : null;

        switch ($step) {
            case 'customer':
                $customer = $this->customer($request);
                $claim = MaximusClaim::create(['customer_id' => $customer->id]);
                return redirect()->route('maximus.claims.create', ['claim_id' => $claim->id, 'step' => 'property']);
                break;

            case 'property':
                if (is_object($property)) {
                    $property = $this->updateProperty($request, $customer->id, $property);
                } else {
                    $property = $this->property($request, $customer->id);
                }
                $request->merge(['property_id' => $property->id]);
                $claim->update($request->all());
                return redirect()->route('maximus.claims.create', ['claim_id' => $claim->id, 'step' => 'insurance']);
                break;

            case 'claim':
                $claim->update($request->all());
                return redirect()->route('maximus.claims.create', ['claim_id' => $claim->id, 'step' => 'documents']);
                break;

            case 'documents':
                $claim->update($request->all());
                break;
        }

        /* $claim = MaximusClaim::create($request->all());

         $customer = Customer::create($request->customer);

         $property = Property::create([
             'client_id' => 1,
             'customer_id' => $customer->id,
             'classification_id' => 3,
             'relationship_id' => 96,
         ]);

         $property->address()->create($request->address);

         $claim->update(['property_id' => $property->id, 'customer_id' => $customer->id]);*/

        ProcessMaximusClaimUploads::dispatch($claim);
        /*$this->generatePhotosPdf($claim, "maximus/$claim->id/aob/");

        $this->uploadDocuments($claim);*/
        /*$this->uploadDocs($claim);*/

        /*Mail::send(new AobSubmitted($claim, $request->template));*/

        return redirect()->route('maximus.claims.index')->with('success', 'Claim Created');
    }

    private function customer(Request $request)
    {
        return Customer::create($request->customer);
    }

    private function property(Request $request, $customer)
    {
        $property = Property::create([
            'client_id' => 1,
            'customer_id' => $customer,
            'classification_id' => 3,
            'relationship_id' => 96,
        ]);
        $property->address()->create($request->address);
        return $property;
    }

    private function updateProperty(Request $request, $customer, $property)
    {
        $property = Property::updateOrCreate(['id' => $property->id], [
            'client_id' => 1,
            'customer_id' => $customer,
            'classification_id' => 3,
            'relationship_id' => 96,
        ]);
        $property->address()->updateOrCreate(['addressable_id' => $property->id], $request->address);
        return $property;
    }

    public function show(MaximusClaim $claim)
    {
        $claim->load([
            'carrierResponses', 'submissions', 'tempRepair', 'media.model',
            'mails.recipients', 'statusLogs.status', 'statusLogs.user',
        ]);

        $data = array();
        $data['emails_to_resend'] = $claim->mails()->with('recipients')->get()->where('resent', 0)->where('forwarded', 0);
        $data['claim'] = $claim;
        $data['temp_repair_template'] = app('assets')->getTemplate('temp_repair_created');
        $data['escalate_template'] = app('assets')->getTemplate('maximus_claim_escalated');
        $data['info_submission_template'] = app('assets')->getTemplate('maximus_info_submitted');

        return view('maximus.show', $data);
    }

    public function update(Request $request, MaximusClaim $claim)
    {
        $claim->update([
            'status_id' => $claim->logStatusChange($request->status_id),
            'description' => $request->description
        ]);
        return redirect()->back()->with('success', 'Claim Status Updated');
    }

    public function tempRepairStore(Request $request, MaximusClaim $claim)
    {
        $request->validate([
            'photos.*' => 'required|mimes:jpeg,png,jpg,gif,svg|min:2',
            'photos' => 'required|min:8|max:8',
            'invoice' => 'required|mimes:pdf',
            'invoice_number' => 'required',
            'invoice_amount' => 'required',
        ]);

        $tempRepair = $claim->tempRepair()->create($request->all());

        $this->generatePhotosPdf($tempRepair);

        $tempRepair->addMediaFromRequest('invoice')
            ->usingName('invoice')
            ->withCustomProperties(['media_type_id' => app('constants')->getAttachmentTypeId('invoice')])
            ->toMediaCollection('documents');


        Mail::send(new TempRepairSubmitted($claim, $tempRepair->getMedia('documents')));

        return redirect()->back()->with('success', 'Temporary Repair Uploaded Successfully');

    }

    public function supplement(Request $request, MaximusClaim $claim)
    {
        $request->validate([
            'type_id' => 'required',
            'document' => 'required|mimes:pdf',
        ]);

        $submission = $claim->submissions()->create();

        $document_name = app('constants')->findById($request->type_id)->name;

        $submission->addMediaFromRequest('document')
            ->usingName($document_name)
            ->withCustomProperties(['media_type_id' => $request->type_id])
            ->toMediaCollection();

        // Evaluating
        $claim->update(['status_id' => $claim->logStatusChange(27)]);

        Mail::send(new InfoSubmitted($claim, $submission->getLastMedia(), $request->template));

        return redirect()->back()->with('success', 'Requested Info Uploaded Successfully')->with('info', 'Status Changed to ' . $claim->status->name);

    }

    public function recordCorrespondence(Request $request, MaximusClaim $claim)
    {
        $request->validate([
            'response_type_id' => 'required',
            'document' => 'required|mimes:pdf',
        ]);

        $carrierResponse = $claim->carrierResponses()->create([
            'response_type_id' => $request->response_type_id,
            'dated_on' => $request->dated_on,
            'received_on' => $request->received_on,
        ]);

        switch ($request->response_type_id) {
            // if it's a decision
            case 55:
                $new_claim_status = 29; // Decided
                $claim->update([
                    'coverage_type_id' => $request->coverage_type_id,
                    'coverage_amount' => $request->coverage_amount,
                    'denial_reason' => $request->denial_reason_id ? app('constants')->findById($request->denial_reason_id)->name : '',
                ]);
                break;

            // if it's an acknowledgement
            case 53:
                $new_claim_status = 25; // Acknowledged
                break;

            default:
                $new_claim_status = 28; // Waiting
        }

        $document_name = app('constants')->findById($request->response_type_id)->name;

        $carrierResponse->addMediaFromRequest('document')
            ->usingName($document_name)
            ->withCustomProperties(['media_type_id' => $request->response_type_id])
            ->toMediaCollection('documents');

        $claim->update(['status_id' => $claim->logStatusChange($new_claim_status)]);

        return redirect()->back()->with('success', 'Record Correspondence Uploaded Successfully')->with('info', 'Status Changed to ' . $claim->status->name);

    }

    public function escalate(Request $request, MaximusClaim $claim)
    {

resources/views/maximus/create.blade.php
@extends('layouts.backend')

@section('styles')
    <link rel="stylesheet" href="{{ asset('js/plugins/flatpickr/flatpickr.min.css') }}">

    <link href="{{ asset('js/plugins/bootstrap-fileinput/css/fileinput.css') }}" media="all" rel="stylesheet"
          type="text/css"/>
    <link href="{{ asset('js/plugins/bootstrap-fileinput//themes/explorer-fas/theme.css') }}" media="all"
          rel="stylesheet" type="text/css"/>
    <link rel="stylesheet" href="{{ asset('js/plugins/jquery-tags-input/jquery.tagsinput.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{asset('js/plugins/summernote/summernote.css')}}">
    <link rel="stylesheet" href="{{ asset('js/plugins/select2/css/select2.min.css') }}">
    <style>
        .select2-container--default .select2-selection--multiple .select2-selection__choice {
            height: 22px;
            line-height: 22px;
            color: #fff;
            font-size: 13px;
            font-weight: 600;
            background-color: #3f9ce8;
            border: none;
            border-radius: 3px;
        }
    </style>
@endsection

@section('breadcrumbs')
    <a class="breadcrumb-item" href="javascript:void(0)">Maximus</a>
@endsection
@section('breadcrumb-active', 'AOB')

@section('content')
    <div class="block">
        <div class="block-header block-header-default">
            <ul class="nav nav-tabs nav-tabs-block  justify-content-end align-items-center" data-toggle="tabs" role="tablist">
                <li class="nav-item">
                    <a class="nav-link {{ _active_tab('step', 'customer', true) }}"
                       href="#customer">Customer</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {{ _active_tab('step', 'property') }}"
                       href="#property">Property</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {{ _active_tab('step', 'insurance') }}"
                       href="#insurance">Insurance</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {{ _active_tab('step', 'documents') }}"
                       href="#documents">Documents</a>
                </li>
            </ul>
        </div>
        <div class="block-content">
            @include('includes.partials.errors')
            {{--<form action="{{ route('maximus.claims.store') }}" method="POST" enctype="multipart/form-data">
                @csrf--}}
                @include('maximus.form')

           {{-- </form>--}}
        </div>
    </div>
@endsection

@section('scripts')
    <script src="{{ asset('js/plugins/jquery-tags-input/jquery.tagsinput.min.js') }}"></script>
    <script src="{{asset('js/plugins/summernote/summernote.min.js')}}"></script>
    <script src="{{ asset('js/plugins/select2/js/select2.full.min.js') }}"></script>
    <script src="{{ asset('js/plugins/flatpickr/flatpickr.min.js') }}"></script>

    <script>
        jQuery(function () {
            Codebase.helper(['summernote', 'flatpickr', 'select2', 'tags-inputs']);
        });
    </script>
    <script>
        $(document).ready(function () {
            let check_box = "#adjuster_meeting_set";
            let parent_id = "#adjuster_meeting_at";
            let parent = $(parent_id).parent('.form-group')
            let meeting_set = $(check_box).is(':checked');

            $(check_box).change(function () {
                meeting_set = $(check_box).is(':checked');
                meeting_set ? parent.show() : visible();
            });
            meeting_set ? parent.show() : visible();

            function visible() {
                $(parent_id).val('');
                parent.hide();
            }
        });
        $(document).on("keydown", ":input:not(textarea):not(:submit)", function(event) {
            if(event.keyCode === 13) {
                event.preventDefault();
                return false;
            }
        });
    </script>
    @include('includes.common.bootstrap-fileinput')

@endsection

resources/views/maximus/index.blade.php
@extends('layouts.backend')

@section('breadcrumbs')
    <a class="breadcrumb-item" href="javascript:void(0)">Maximus</a>
@endsection
@section('breadcrumb-active', 'Claims')

@section('styles')
    <link href="{{ asset('js/plugins/datatables/dataTables.bootstrap4.css') }}" rel='stylesheet'>
@endsection

@section('content')
    <div class="block">
        <div class="block-header block-header-default">
            <h3 class="block-title">Assigned Claims Outstanding</h3>
            <div class="block-options">
                {{--@include('includes.common.search', ['route' => route('maximus.claims.index')])--}}
            </div>
        </div>
        <div class="block-content">
            <div class="table-responsive">
                <table class="table table-striped table-vcenter js-dataTable-full"  data-page-length='20' data-order='[[0, "desc"]]'>
                    <thead>
                    <tr>
                        <th style="width: 10px">#</th>
                        <th>Policy Holder(s)</th>
                        <th>Property Address</th>
                        <th>Status</th>
                        <th>Submitted</th>
                        <th>Estimator</th>
                        <th style="width: 50px">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @forelse($claims as $claim)
                        <tr>
                            <td>{{ $claim->id }}</td>
                            <td>
                                {{ $claim->customer->name }}
                                @if($claim->customer->secondary_name)
                                    <br>
                                    {{ $claim->customer->secondary_name }}
                                @endif
                            </td>
                            <td>{{$claim->property? $claim->property->full_address : '' }}</td>
                            <td>{{ $claim->status->name }}</td>
                            <td>@formattedDate($claim->submitted_at)</td>
                            <td>{{ $claim->estimator->name }}</td>
                            <td class="text-center">
                                <div class="btn-group">
                                    <a href="{{ route('maximus.claims.show', $claim->id ) }}"
                                       class="btn btn-sm btn-secondary"
                                       data-toggle="tooltip" title="Show">
                                        <i class="fad fa-eye"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="999" class="text-center">{{ app('constants')->constant('no_record') }}</td>
                        </tr>
                    @endforelse
                    </tbody>
                </table>

                {{--<div class="pagination justify-content-center">
                    {{ $claims->links() }}
                </div>--}}
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="{{ asset('js/plugins/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('js/plugins/datatables/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('js/pages/tables_datatables.js') }}"></script>
@endsection

resources/views/maximus/photos.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Maximus Photos</title>
    <style>
        td{
            background: #f0f0f0;
            padding: 10px;
            border: 1px solid #d3d3d3;
        }
    </style>
</head>

<body>
<h5>Check the photos below for damage</h5>

<div style="text-align: center; width: 100%">
    <table width="100%" style="table-layout: fixed">
        <tr>
            <td width="50%"><img src="{{ ($photos[0]) }}" style="width: 100%;height: 500px;object-fit: contain"></td>
            <td width="50%"><img src="{{ ($photos[1]) }}" style="width: 100%;height: 500px;object-fit: contain"></td>
        </tr>
        <tr>
            <td width="50%"><img src="{{ ($photos[2]) }}" style="width: 100%;height: 500px;object-fit: contain"></td>
            <td width="50%"><img src="{{ ($photos[3]) }}" style="width: 100%;height: 500px;object-fit: contain"></td>
        </tr>
    </table>
    <div style="page-break-before: always;"></div>
    <table width="100%" style="table-layout: fixed">
        <tr>
            <td width="50%"><img src="{{ ($photos[4]) }}" style="width: 100%;height: 500px;object-fit: contain"></td>
            <td width="50%"><img src="{{ ($photos[5]) }}" style="width: 100%;height: 500px;object-fit: contain"></td>
        </tr>
        <tr>
            <td width="50%"><img src="{{ ($photos[6]) }}" style="width: 100%;height: 500px;object-fit: contain"></td>
            <td width="50%"><img src="{{ ($photos[7]) }}" style="width: 100%;height: 500px;object-fit: contain"></td>
        </tr>
    </table>
</div>



</body>
</html>