routes/web.php
<?php

Auth::routes(['verify' => true]);
Route::mailgunWebhooks('webhooks/mailgun');

Route::get('/', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth', 'verified']], function () {
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

    Route::get('/customersign/{token}', 'EstimateController@customersign')->name('customersign');
    Route::post('/customersign', 'EstimateController@customerDosign');
    Route::post('/customersign/verify', 'EstimateController@customerVerify');

    /*Project Routes*/
    //Route::resource('projects', 'ProjectController')->except(['destroy']);
    Route::get('/projects', 'ProjectController@index')->name('projects.index');
    Route::get('projects/create', 'ProjectController@create')->name('projects.create');
    Route::post('projects/{step}', 'ProjectController@store')->name('projects.steps.store');
    //Route::get("/testemail",'ProjectController@basic_email');

    Route::group(['prefix' => 'estimator'], function () {
        Route::get('/buildlists', 'BuildListController@index')->name('estimator.buildlists');
        Route::get('/buildlists/build', 'BuildListController@create')->name('estimator.buildlists.build');
        Route::get('/{step?}', 'EstimatorController@index')->name('estimator.index');

        Route::get('/{project}/structure-details', 'EstimatorController@getStructureDetails')->name('estimator.structure_details');
        Route::post('/{project}/structure', 'EstimatorController@storeStructure')->name('estimator.structure.store');

        Route::get('/{project}/roof-selector', 'EstimatorController@roofSelector')->name('estimator.roof_selector');
        Route::post('/{project}/roof-selector', 'StructureController@storeRoofType')->name('estimator.roof_selector');

        Route::post('/{project}/estimate', 'EstimatorController@estimate')->name('estimator.estimate');
    });

    Route::get('/estimator/numbers', 'EstimateController@numbers')->name('numbers');

    Route::post('/estimator/calculate', 'EstimateController@store');
    Route::post('/estimator/store', 'PropertyController@store')->name('properties.store');
    Route::get('/estimator/create-estimate', 'EstimateController@create')->name('myestimates');
    Route::get('/estimator/estimate-figures', 'EstimateController@showCalculationResult')->name('estimate-figures');
    Route::get('/estimator/generateProposal', 'EstimateController@generateProposal')->name('generateProposal');
    /*proposal send*/
    Route::post('/estimator/generateProposal/{id}/send', 'EstimateController@generateProposalSend')->name('generateProposalSend');

    /*Harvester Views*/
    Route::get('/harvester/market', 'HarvesterController@market')->name('market');                      // Gabe working on this interface
    Route::get('/harvester/candidates', 'HarvesterController@candidates')->name('candidates');          // Gabe working on this interface

    Route::get('/estimator/generatePDF', 'EstimateController@generatePDF')->name('generatePDF');


    Route::get('/signer/docs', 'DocumentsController@index')->name('docs');

    Route::post('appointments/{appointment}/update-time', 'AppointmentController@updateTime');
    Route::resource('appointments', 'AppointmentController');

    Route::resource('users', 'UserController');
    Route::resource('materials', 'MaterialController');

    Route::get('tasks/{task}/complete', 'TaskController@complete')->name('tasks.complete');
    Route::resource('tasks', 'TaskController')->only(['index', 'create', 'store']);

    ## Gabe Playground
    Route::get('/email', 'HomeController@email')->name('email');        // Gabe messing around with Sendgrid

    /*Project Routes*/
    Route::resource('customers', 'CustomerController')->except(['destroy']);

    /* Maximus routes */
    Route::group(['prefix' => 'maximus/claims'], function () {
        Route::get('/', 'MaximusController@index')->name('maximus.claims.index');
        Route::get('new', 'MaximusController@create')->name('maximus.claims.create');
        Route::post('/{step}', 'MaximusController@store')->name('maximus.claims.step.store');
//        Route::post('new', 'MaximusController@store')->name('maximus.claims.store');
        Route::get('{claim}/show', 'MaximusController@show')->name('maximus.claims.show');
        Route::post('{claim}/update', 'MaximusController@update')->name('maximus.claims.update');
        Route::post('{claim}/temp-repair', 'MaximusController@tempRepairStore')->name('maximus.temp_repair.store');
        Route::post('{claim}/supplement', 'MaximusController@supplement')->name('maximus.supplement.store');
        Route::post('{claim}/record-correspondence', 'MaximusController@recordCorrespondence')->name('maximus.record_correspondence.store');
        Route::post('{claim}/escalate', 'MaximusController@escalate')->name('maximus.escalate');
        Route::get('{claim}/test', 'MaximusController@test');
    });

    Route::resource('insurance-carriers', 'InsuranceCarrierController')->names([
        'create' => 'insurance_carriers.create',
        'store' => 'insurance_carriers.store',
        'index' => 'insurance_carriers.index',
        'destroy' => 'insurance_carriers.destroy',
        'update' => 'insurance_carriers.update',
        'show' => 'insurance_carriers.show',
        'edit' => 'insurance_carriers.edit',
    ]);

    ## Khawar working area
    Route::group(['prefix' => 'settings'], function () {
        Route::view('/company', 'settings/company/show')->name('settings.company.show');
        Route::view('/company/edit', 'settings/company/edit')->name('settings.company.edit');
    });

    Route::name('templates.')->prefix('templates')->group(function () {
        Route::get('emails/{template}/changeStatus', 'EmailTemplateController@changeStatus')->name('emails.change_status');

        Route::resource('emails', 'EmailTemplateController')->parameters(['emails' => 'template']);
    });


    Route::get('constants', 'GroupConstantController')->name('constants.index');
    Route::resource('placeholders', 'PlaceholderController');

    Route::get('emails/odmails', 'OdMailController@index')->name('emails.odmails');
    Route::get('emails/odmail/{odmail}', 'OdMailController@show')->name('emails.odmails.show');
    Route::get('emails/odmail/{odmail}/resend', 'OdMailController@resend')->name('emails.odmails.resend');
    Route::post('emails/odmail/{odmail}/forward', 'OdMailController@forward')->name('emails.odmails.forward');

    Route::resource('campaigns', 'CampaignController');
    Route::get('campaigns/{campaign}/recipients', 'CampaignController@recipients')->name('campaigns.recipients');

    Route::get('developer-tools/logs', 'DeveloperTools\LogsController@index')->name('developer_tools.logs');
    Route::get('developer-tools/logs/{file}', 'DeveloperTools\LogsController@show')->name('developer_tools.logs.show');
    Route::delete('developer-tools/logs/{file}', 'DeveloperTools\LogsController@truncate')->name('developer_tools.logs.truncate');

});
Route::view('/frontend', 'frontend/frontend')->name('frontend');

app/Project.php
<?php

namespace App;

use App\Traits\HasClient;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\DB;

class Project extends Model
{
    use SoftDeletes;
    use HasClient;

    public $timestamps = true;

    protected $fillable = [
        'customer_id', 'phase_id', 'user_id', 'project_type', 'property_id', 'name', 'billing_address_id',
        'description', 'current_roof_type_id', 'preferred_roof_type_id', 'customer_notes'
    ];

    /************* Relationships **************/
    public function phase()
    {
        return $this->belongsTo(Phase::class);
    }

    public function customer()
    {
        return $this->belongsTo(Customer::class);
    }

    public function property()
    {
        return $this->belongsTo(Property::class);
    }

    public function structures()
    {
        return $this->hasMany(Structure::class);
    }

    public function estimator()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function estimates()
    {
        return $this->hasMany(Estimate::class);
    }

    /************* Attributes **************/

    public function getLabelAttribute()
    {
        return $this->customer->last_name .'-'. $this->property->city_name;
    }

    public function getTitleAttribute()
    {
        return $this->customer->last_name .'-'. $this->property->address->city;
    }

    public function getAddressAttribute()
    {
        return $this->property->address->full_address;
    }

    public function getCurrentMaterialNameAttribute()
    {
        return RoofType::where('id', $this->current_roof_type_id)->first()->name;
    }

    public function getPreferredMaterialNameAttribute()
    {
        return RoofType::where('id', $this->preferred_roof_type_id)->first()->name;
    }

    public function getProjectTypeAttribute()
    {
        return app('constants')->getName($this->project_type_id, 'project_types');
    }

    public function getRelationshipName()
    {
        return app('constants')->getName($this->property->relationship_id);
    }
}

app/Http/Controllers/EstimatorController.php
<?php

namespace App\Http\Controllers;

use App\Constant;
use App\Material;
use App\Project;
use App\RoofType;
use App\Services\Estimator;
use Illuminate\Http\Request;

class EstimatorController extends Controller
{
    public function index($step = null)
    {
        $projects = Project::all();
        info('inside Project');
        return view('estimator.index', compact('projects', 'step'));
    }

    public function getStructureDetails(Project $project)
    {
        $data = [
            'project' => $project,
            'pitch_types' => Constant::group('pitch_types')->get(),
            'story_types' => Constant::group('story_types')->get(),
            'penetration_types' => ['boot' =>  Material::boots()->get(), 'vent' => Material::vents()->get()]
        ];

        return view('estimator.structure-details', $data);
    }

    public function storeStructure(Request $request, Project $project)
    {
        $request->validate([
           'measurements.square_feet' => 'required'
        ]);
        $project->structures()->create($request->all());
        return redirect()->route('estimator.roof_selector', $project->id)->with('success', 'Structure Details Saved');
    }

    public function roofSelector(Project $project)
    {
        $data = array();
        $data['project'] = $project;
        $data['roof_type_groups'] = RoofType::with('roofTypes.manufacturers.productLines.series')->groups()->get();

        return view('estimator.roof-selector', $data);
    }

    public function estimate(Request $request, Project $project){
        $structure = $project->structures->first();

        /*$estimate = $structure->estimates()->firstOrCreate([
            'user_id' => auth()->user()->id,
            'roof_product_id' => $request->series_id ?? $request->product_id
        ]);
        $estimator = new Estimator($estimate);
        $buildSheets = $estimator->generateBuildSheets();
        $estimate->buildSheets()->createMany($buildSheets);*/
        $estimate = $structure->estimates->first();
        return view('estimator.estimate', compact('estimate', 'project'));
    }
}

resources/views/estimator/estimate.blade.php
@extends('layouts.backend')

@section('breadcrumbs')
    <a class="breadcrumb-item" href="javascript:void(0)">Estimator</a>
@endsection
@section('breadcrumb-active', 'Estimate Result')

@section('content-header-action')
    <button>fsf</button>
@endsection

@section('content')
        <!-- Project Details -->
        <h2 class="content-heading pt-2">Project Details</h2>
        <div class="row row-deck gutters-tiny">
            <!-- Billing Address -->
            <div class="col-md-6">
                <div class="block block-rounded">
                    <div class="block-header block-header-default">
                        <h3 class="block-title">Customer Details</h3>
                    </div>
                    <div class="block-content">
                        <div class="font-size-lg text-black mb-5">{{ $project->customer->name }}</div>
                        <address>
                            {{ $project->customer->address->street }}<br>
                            {{ $project->customer->address->city }} {{ $project->customer->address->zip_code }}<br>
                            {{ $project->customer->address->country }}<br><br>
                            <i class="fa fa-phone mr-5"></i> {{ $project->customer->phone }}<br>
                            <i class="fa fa-envelope-o mr-5"></i> <a href="javascript:void(0)">{{ $project->customer->email }}</a>
                        </address>
                    </div>
                </div>
            </div>
            <!-- END Billing Address -->

            <!-- Shipping Address -->
            <div class="col-md-6">
                <div class="block block-rounded">
                    <div class="block-header block-header-default">
                        <h3 class="block-title">Structure Details</h3>
                    </div>
                    <div class="block-content">
                        <div class="font-size-lg text-black mb-5">{{ $project->preferred_material_name }} - {{ $project->project_type }}</div>
                        <address>
                            5110 8th Ave<br>
                            New York 11220<br>
                            United States<br><br>
                            <i class="fa fa-phone mr-5"></i> (999) 111-222222<br>
                            <i class="fa fa-envelope-o mr-5"></i> <a href="javascript:void(0)">company@example.com</a>
                        </address>
                    </div>
                </div>
            </div>
            <!-- END Shipping Address -->
        </div>
        <!-- END Addresses -->

        <!-- Products -->
        <h2 class="content-heading">
            Build Sheets ({{ $estimate->buildSheets->count() }})
            <div class="float-right">
                <label class="css-control css-control-sm css-control-primary css-switch">
                    <input type="checkbox" class="css-control-input" checked="">
                    Show Actual Cost  <span class="css-control-indicator"></span>
                </label>
            </div>
        </h2>
        <div class="block block-rounded">
            <div class="block-content">
                <div class="table-responsive">
                    <table class="table table-borderless table-striped">
                        <thead>
                        <tr>
                            <th>Type</th>
                            <th>Name</th>
                            <th>Unit</th>
                            <th>Qty</th>
                            <th>Unit Price</th>
                            <th>Waste Factor</th>
                            <th>Total Cost</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($estimate->buildSheets as $build_sheet)
                        <tr>
                            <td>{{ Str::studly($build_sheet->type) }}</td>
                            <td>{{ $build_sheet->name }}</td>
                            <td>{{ $build_sheet->unit }}</td>
                            <td class="font-w600">
                                {{ $build_sheet->actual_quantity }}
                                @if($build_sheet->waste_factor) (+{{ $build_sheet->additional_quantity }}) @endif
                            </td>
                            <td>${{ $build_sheet->unit_price }}</td>
                            <td>{{ $build_sheet->waste_factor ? $build_sheet->waste_factor : '-' }}</td>
                            <td>
                                ${{ $build_sheet->cost }}
                                @if($build_sheet->waste_factor)(+{{ $build_sheet->waste_factor_cost }}) @endif
                            </td>
                        </tr>
                        @endforeach
                        <tr>
                            <td colspan="6" class="text-right font-w600">Sub Total:</td>
                            <td class="text-right">${{ $estimate->buildSheets->sum('cost') }}</td>
                        </tr>
                        <tr>
                            <td colspan="6" class="text-right font-w600">Additional Cost:</td>
                            <td class="text-right">${{ $estimate->buildSheets->sum('waste_factor_cost') }}</td>
                        </tr>
                        <tr>
                            <td colspan="6" class="text-right font-w600">Material Profit:</td>
                            <td class="text-right">${{ $estimate->buildSheets->sum('waste_factor_cost') }}</td>
                        </tr>
                        <tr>
                            <td colspan="6" class="text-right font-w600">Labor Profit:</td>
                            <td class="text-right">${{ $estimate->buildSheets->sum('waste_factor_cost') }}</td>
                        </tr>
                        <tr class="table-success">
                            <td colspan="6" class="text-right font-w600 text-uppercase">Total Cost:</td>
                            <td class="text-right font-w600">${{ $estimate->buildSheets->sum('total_cost') }}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- END Products -->
@endsection

resources/views/estimator/index.blade.php
@extends('layouts.backend')

@section('breadcrumbs')
    <a class="breadcrumb-item" href="javascript:void(0)">Estimator</a>
@endsection
@section('breadcrumb-active', 'Select Project')

@section('content-heading', 'Select Project')

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="block">
                <div class="block-header block-header">
                    <h3 class="block-title">Projects List</h3>
                    <div class="block-options">
                        @include('includes.common.search', ['route' => route('projects.index')])
                    </div>
                </div>
                <div class="block-content">
                    <table class="table table-striped table-vcenter">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Address</th>
                            <th>Created</th>
                            <th>Modified</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        @forelse($projects as $project)
                            <tr>
                                <td>{{ $project->title }}</td>
                                <td>{{ $project->address }}</td>
                                <td>{{ $project->created_at->format('D M j, Y g:i a') }}</td>
                                <td>{{ $project->updated_at->format('D M j, Y g:i a') }}</td>
                                @php($route = $step == 'roof-selector' ? 'estimator.roof_selector' : 'estimator.structure_details')
                                <td><a href="{{ route($route, $project->id) }}" class="btn btn-sm btn-primary">Proceed</a></td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="999" class="text-center">{{ _constant('no_record') }}</td>
                            </tr>
                        @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/estimator/roof-selector.blade.php
@extends('layouts.backend')

@section('breadcrumbs')
    <a class="breadcrumb-item" href="javascript:void(0)">Estimator</a>
@endsection
@section('breadcrumb-active', 'Roof Selector')

@section('content-heading', 'Step 1 - Select Roof Type')

@section('content')
    <form action="{{ route('estimator.estimate', $project->id) }}" method="post">
        @csrf
        <roof-selector :roof-type-groups="{{ json_encode($roof_type_groups) }}"></roof-selector>
    </form>
@endsection