routes/web.php
<?php

Auth::routes(['verify' => true]);
Route::mailgunWebhooks('webhooks/mailgun');

Route::get('/', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth', 'verified']], function () {
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

    Route::get('/customersign/{token}', 'EstimateController@customersign')->name('customersign');
    Route::post('/customersign', 'EstimateController@customerDosign');
    Route::post('/customersign/verify', 'EstimateController@customerVerify');

    /*Project Routes*/
    //Route::resource('projects', 'ProjectController')->except(['destroy']);
    Route::get('/projects', 'ProjectController@index')->name('projects.index');
    Route::get('projects/create', 'ProjectController@create')->name('projects.create');
    Route::post('projects/{step}', 'ProjectController@store')->name('projects.steps.store');
    //Route::get("/testemail",'ProjectController@basic_email');

    Route::group(['prefix' => 'estimator'], function () {
        Route::get('/buildlists', 'BuildListController@index')->name('estimator.buildlists');
        Route::get('/buildlists/build', 'BuildListController@create')->name('estimator.buildlists.build');
        Route::get('/{step?}', 'EstimatorController@index')->name('estimator.index');

        Route::get('/{project}/structure-details', 'EstimatorController@getStructureDetails')->name('estimator.structure_details');
        Route::post('/{project}/structure', 'EstimatorController@storeStructure')->name('estimator.structure.store');

        Route::get('/{project}/roof-selector', 'EstimatorController@roofSelector')->name('estimator.roof_selector');
        Route::post('/{project}/roof-selector', 'StructureController@storeRoofType')->name('estimator.roof_selector');

        Route::post('/{project}/estimate', 'EstimatorController@estimate')->name('estimator.estimate');
    });

    Route::get('/estimator/numbers', 'EstimateController@numbers')->name('numbers');

    Route::post('/estimator/calculate', 'EstimateController@store');
    Route::post('/estimator/store', 'PropertyController@store')->name('properties.store');
    Route::get('/estimator/create-estimate', 'EstimateController@create')->name('myestimates');
    Route::get('/estimator/estimate-figures', 'EstimateController@showCalculationResult')->name('estimate-figures');
    Route::get('/estimator/generateProposal', 'EstimateController@generateProposal')->name('generateProposal');
    /*proposal send*/
    Route::post('/estimator/generateProposal/{id}/send', 'EstimateController@generateProposalSend')->name('generateProposalSend');

    /*Harvester Views*/
    Route::get('/harvester/market', 'HarvesterController@market')->name('market');                      // Gabe working on this interface
    Route::get('/harvester/candidates', 'HarvesterController@candidates')->name('candidates');          // Gabe working on this interface

    Route::get('/estimator/generatePDF', 'EstimateController@generatePDF')->name('generatePDF');


    Route::get('/signer/docs', 'DocumentsController@index')->name('docs');

    Route::post('appointments/{appointment}/update-time', 'AppointmentController@updateTime');
    Route::resource('appointments', 'AppointmentController');

    Route::resource('users', 'UserController');
    Route::resource('materials', 'MaterialController');

    Route::get('tasks/{task}/complete', 'TaskController@complete')->name('tasks.complete');
    Route::resource('tasks', 'TaskController')->only(['index', 'create', 'store']);

    ## Gabe Playground
    Route::get('/email', 'HomeController@email')->name('email');        // Gabe messing around with Sendgrid

    /*Project Routes*/
    Route::resource('customers', 'CustomerController')->except(['destroy']);

    /* Maximus routes */
    Route::group(['prefix' => 'maximus/claims'], function () {
        Route::get('/', 'MaximusController@index')->name('maximus.claims.index');
        Route::get('new', 'MaximusController@create')->name('maximus.claims.create');
        Route::post('/{step}', 'MaximusController@store')->name('maximus.claims.step.store');
//        Route::post('new', 'MaximusController@store')->name('maximus.claims.store');
        Route::get('{claim}/show', 'MaximusController@show')->name('maximus.claims.show');
        Route::post('{claim}/update', 'MaximusController@update')->name('maximus.claims.update');
        Route::post('{claim}/temp-repair', 'MaximusController@tempRepairStore')->name('maximus.temp_repair.store');
        Route::post('{claim}/supplement', 'MaximusController@supplement')->name('maximus.supplement.store');
        Route::post('{claim}/record-correspondence', 'MaximusController@recordCorrespondence')->name('maximus.record_correspondence.store');
        Route::post('{claim}/escalate', 'MaximusController@escalate')->name('maximus.escalate');
        Route::get('{claim}/test', 'MaximusController@test');
    });

    Route::resource('insurance-carriers', 'InsuranceCarrierController')->names([
        'create' => 'insurance_carriers.create',
        'store' => 'insurance_carriers.store',
        'index' => 'insurance_carriers.index',
        'destroy' => 'insurance_carriers.destroy',
        'update' => 'insurance_carriers.update',
        'show' => 'insurance_carriers.show',
        'edit' => 'insurance_carriers.edit',
    ]);

    ## Khawar working area
    Route::group(['prefix' => 'settings'], function () {
        Route::view('/company', 'settings/company/show')->name('settings.company.show');
        Route::view('/company/edit', 'settings/company/edit')->name('settings.company.edit');
    });

    Route::name('templates.')->prefix('templates')->group(function () {
        Route::get('emails/{template}/changeStatus', 'EmailTemplateController@changeStatus')->name('emails.change_status');

        Route::resource('emails', 'EmailTemplateController')->parameters(['emails' => 'template']);
    });


    Route::get('constants', 'GroupConstantController')->name('constants.index');
    Route::resource('placeholders', 'PlaceholderController');

    Route::get('emails/odmails', 'OdMailController@index')->name('emails.odmails');
    Route::get('emails/odmail/{odmail}', 'OdMailController@show')->name('emails.odmails.show');
    Route::get('emails/odmail/{odmail}/resend', 'OdMailController@resend')->name('emails.odmails.resend');
    Route::post('emails/odmail/{odmail}/forward', 'OdMailController@forward')->name('emails.odmails.forward');

    Route::resource('campaigns', 'CampaignController');
    Route::get('campaigns/{campaign}/recipients', 'CampaignController@recipients')->name('campaigns.recipients');

    Route::get('developer-tools/logs', 'DeveloperTools\LogsController@index')->name('developer_tools.logs');
    Route::get('developer-tools/logs/{file}', 'DeveloperTools\LogsController@show')->name('developer_tools.logs.show');
    Route::delete('developer-tools/logs/{file}', 'DeveloperTools\LogsController@truncate')->name('developer_tools.logs.truncate');

});
Route::view('/frontend', 'frontend/frontend')->name('frontend');

app/Customer.php
<?php

namespace App;

use App\Traits\HasClient;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\DB;

class Customer extends People
{
    use Notifiable;
    use HasClient;

    protected $table = 'peoples';

    public static function getLeadSources() {
        $lead_sources = DB::table('lead_sources')->get();
        return $lead_sources;
    }

    public function project()
    {
        return $this->hasOne(Project::class)->first();
    }

}

app/Http/Controllers/Api/CustomerController.php
<?php

namespace App\Http\Controllers\Api;

use App\Customer;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CustomerController extends Controller
{

    public function index()
    {
        //
    }


    public function store(Request $request)
    {
        $request->validate([
            'first_name' => 'required',
            'last_name' => 'required',
            'email' => 'required',
            'cell_phone' => 'required',
        ]);
        $customer = Customer::create($request->all());
        return response($customer);
    }


    public function show($id)
    {
        //
    }


    public function update(Request $request, $id)
    {
        //
    }

    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use App\Constant;
use App\Phase;
use App\Property;
use GuzzleHttp\Client;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use App\Project;
use App\Address;
use App\Customer;
use App\User;
use Illuminate\Support\Facades\Http;
use App\Services\Datalab\Datalab;

class CustomerController extends Controller
{
    
    public function index()
    {
        $projects = Project::all();
        return view('customer.index', compact('projects'));
    }

    
    public function create()
    {
        return view('customer.create');
    }

    
    public function store(Request $request)
    {
        //

    }

    
    public function show(Customer $customer, Request $request, Datalab $datalab)
    {
        
        $customer_social = [];
        // customer social link
        // get social link by email
        $params = [
            'email' => $customer->email
        ];
        $response = $datalab->getPersonData($params);
        
        if (count($response) > 0 && count($response['profiles']) > 0){
            $customer_social = $response['profiles'];
        }
        
        //estimator social link
        //get by email
        $estimator_social = [];
        $params = [
            'email' => $customer->project()->estimator->email
        ];
        $response = $datalab->getPersonData($params);
        if (count($response) > 0 && count($response['profiles']) > 0){
            $estimator_social = $response['profiles'];
        }
        $data = [
            'customer' => $customer,
            'project' => $customer->project(),
            'estimators' => User::role('estimator')->get(),
            'phases' => Phase::all(),
            'customer_social' => $customer_social,
            'estimator_social' => $estimator_social
        ];
        return view('customer.show', $data);
    }

    
    public function edit(Customer $customer)
    {
        // similar to create but a put
    }

    
    public function update(Request $request, Customer $customer)
    {
        //
    }

    public function destroy(Customer $customer)
    {
        //
    }
}

resources/views/customer/index.blade.php
@extends('layouts.backend')

@section('styles')
<link href="{{ asset('js/plugins/datatables/dataTables.bootstrap4.css') }}" rel='stylesheet'>
<style type="text/css">
tr:hover{
    background-color: #eee !important; 
}
</style>
@endsection
@section('breadcrumbs')
<a class="breadcrumb-item" href="javascript:void(0)">Customers</a>
@endsection

@section('breadcrumb-active', 'All')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="block">
                <div class="block-header block-header-default">
                    <h3 class="block-title">Customers List</h3>
                </div>
                <div class="block-content">
                    <table class="table table-bordered table-striped table-vcenter js-dataTable-full">
                        <thead>
                            <tr>
                                <th class="text-center" style="width:25px;">No</th>
                                <th class="text-center">Customer Name</th>
                                <th class="text-center">Email</th>
                                <th class="text-center" style="width:40%" >Address</th>
                                <th class="text-center">Created Date</th>
                                <th class="text-center">Profile</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php $index = 0; ?>
                            @foreach($projects as $project)
                            <tr>
                                <td class="text-center"><?php $index++; echo $index; ?></td>
                                <td class="text-center font-w600">{{ ucfirst($project->customer->first_name) }} {{ ucfirst($project->customer->last_name) }}</td>
                                <td class="text-center ">{{$project->customer->email}}</td>
                                <td class="text-center">
                                    {{$project->property->address->street}}, {{$project->property->address->city}}, {{$project->property->address->state}}, {{$project->property->address->zip_code}}
                                </td>
                                <td class="text-center ">{{ $project->created_at->format('D M j, Y g:i a') }}</td>
                                <td class="text-center">
                                    <a href="{{ route('customers.show', [$project->customer_id]) }}" class="btn btn-sm btn-secondary" data-toggle="tooltip" title="View Customer">
                                        <i class="fa fa-user"></i>
                                    </a>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
<script src="{{ asset('js/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('js/plugins/datatables/dataTables.bootstrap4.min.js') }}"></script>
<script>
    jQuery(".js-dataTable-full").dataTable({
        columnDefs: [{ orderable: !1, targets: [4] }],
        pageLength: 10,
        lengthMenu: [
            [5, 10, 15, 20],
            [5, 10, 15, 20],
        ],
        autoWidth: !1,
        "oLanguage": {
         "sInfo": "Showing  _START_  to  _END_  of  _TOTAL_  Customers",
         "sInfoEmpty": "Showing  0  to  0  of  0  Customers",
         "sLengthMenu": "Show _MENU_ Customers",
        }
    });
</script>
@endsection